### ISSUE TITLE
NullPointerException crash on startup when using Pickpocketer with Lumen/Illuminations

### ISSUE THREAD

**Issue by floral-qua-floral** [Quarris/PickPocketer#3]
Howdy! The mod looks really neat, but I'm getting a crash with the [Lumen](https://www.curseforge.com/minecraft/mc-mods/illuminations) mod (or Illuminations - however, the 1.12.2 version is still called Lumen, so it's the name I'm using for this report), which adds fireflies and other such tiny glowing things.

To reproduce:
1. Set up a new Forge profile for 1.12.2
2. Include the latest version of Pickpocketer and the most recent 1.12.2 version of Lumen (available [here](https://www.curseforge.com/minecraft/mc-mods/illuminations/files/2594423))
3. Attempt to launch the game. A crash will occur.

Crash report:
[crash-2020-05-27_23.32.17-client.txt](https://github.com/Quarris/PickPocketer/files/4693083/crash-2020-05-27_23.32.17-client.txt)

**Comment by Quarris** [comment]
Having a deeper look this is the fault of Lumen, they create an entity before it is registered so when I try and do entity lookup it cant find it. I would assume they won't fix it on their end since its 1.12 I guess I can do a check to at least prevent the crash. Other than the crash on startup there should (hopefully) be no other compatibility conflicts. Ill release a new version soon.

Edit: Thanks for a good issue post. You included the exact file to download and everything, made things much less of a pain to debug <3

**Comment by Quarris** [comment]
It should be on Curseforge soon
